tasks:
  - name: ruby
    init: |
      bundle install
      cd examples
      bundle install
  - name: gcloud-cli
    init: |
      sudo apt-get install apt-transport-https ca-certificates gnupg -y
      echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
      sudo apt-get update && sudo apt-get install google-cloud-cli -y
  - name: azure-cli
    init: |
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - name: aws-cli
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - wingrunr21.vscode-ruby
    - rebornix.ruby
