tasks:
  - name: ruby
    init: |
      bundle install
      cd examples
      bundle install
  - name: aws-cli
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - wingrunr21.vscode-ruby
    - rebornix.ruby
