# frozen_string_literal: true

source "https://rubygems.org"

gem 'cloud_project_bootcamp_validation_tool', path: "/workspace/cloud-project-bootcamp-validation-tool"
gem 'dotenv', groups: [:development, :test]
gem 'rake'
gem 'ox'