class Cpbvt::Payloads::Aws::Commands
  include Cpbvt::Payloads::Aws::CommandsModules::Acm
  include Cpbvt::Payloads::Aws::CommandsModules::Apigatewayv2
  include Cpbvt::Payloads::Aws::CommandsModules::Cloudformation
  include Cpbvt::Payloads::Aws::CommandsModules::Cloudfront
  include Cpbvt::Payloads::Aws::CommandsModules::Codebuild
  include Cpbvt::Payloads::Aws::CommandsModules::Codepipeline
  include Cpbvt::Payloads::Aws::CommandsModules::CognitoIdp
  include Cpbvt::Payloads::Aws::CommandsModules::Dynamodb
  include Cpbvt::Payloads::Aws::CommandsModules::Dynamodbstreams
  include Cpbvt::Payloads::Aws::CommandsModules::Ec2
  include Cpbvt::Payloads::Aws::CommandsModules::Ecr
  include Cpbvt::Payloads::Aws::CommandsModules::Ecs
  include Cpbvt::Payloads::Aws::CommandsModules::Elbv2
  include Cpbvt::Payloads::Aws::CommandsModules::Lambda
  include Cpbvt::Payloads::Aws::CommandsModules::Rds
  include Cpbvt::Payloads::Aws::CommandsModules::Route53
  include Cpbvt::Payloads::Aws::CommandsModules::S3api
  include Cpbvt::Payloads::Aws::CommandsModules::Servicediscovery
end